{"name": "Process a phone order with Save and then Pay", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'ERROR IS Message: \\nStacktrace:\\nNoSuchElementError: An element could not be located on the page using the given sear...ata\\\\Roaming\\\\npm\\\\node_modules\\\\appium\\\\node_modules\\\\@appium\\\\base-driver\\\\lib\\\\basedriver\\\\commands\\\\find.ts:75:12)' == True\n +  where 'ERROR IS Message: \\nStacktrace:\\nNoSuchElementError: An element could not be located on the page using the given sear...ata\\\\Roaming\\\\npm\\\\node_modules\\\\appium\\\\node_modules\\\\@appium\\\\base-driver\\\\lib\\\\basedriver\\\\commands\\\\find.ts:75:12)' = order('Phone Order')\n +    where order = <logic.takeout_logic.Calculations object at 0x000001971636F340>.order\n +      where <logic.takeout_logic.Calculations object at 0x000001971636F340> = <test_cash.test_phoneorder_cash.TestPhoneOrderCash object at 0x00000197162CA920>.phone", "trace": "self = <test_cash.test_phoneorder_cash.TestPhoneOrderCash object at 0x00000197162CA920>\n\n    @allure.story(\"Phone Order Save and Update and Pay\")\n    @allure.title(\"Process a phone order with Save and then Pay\")\n    def test_phoneorder_update_pay(self):\n    \n>       assert self.phone.order(\"Phone Order\") == True\nE       AssertionError: assert 'ERROR IS Message: \\nStacktrace:\\nNoSuchElementError: An element could not be located on the page using the given sear...ata\\\\Roaming\\\\npm\\\\node_modules\\\\appium\\\\node_modules\\\\@appium\\\\base-driver\\\\lib\\\\basedriver\\\\commands\\\\find.ts:75:12)' == True\nE        +  where 'ERROR IS Message: \\nStacktrace:\\nNoSuchElementError: An element could not be located on the page using the given sear...ata\\\\Roaming\\\\npm\\\\node_modules\\\\appium\\\\node_modules\\\\@appium\\\\base-driver\\\\lib\\\\basedriver\\\\commands\\\\find.ts:75:12)' = order('Phone Order')\nE        +    where order = <logic.takeout_logic.Calculations object at 0x000001971636F340>.order\nE        +      where <logic.takeout_logic.Calculations object at 0x000001971636F340> = <test_cash.test_phoneorder_cash.TestPhoneOrderCash object at 0x00000197162CA920>.phone\n\nAutomation-logic\\suits\\test_orderflows\\test_cash\\test_phoneorder_cash.py:45: AssertionError"}, "start": 1742910262037, "stop": 1742910272905, "uuid": "23285e88-6de6-4226-83da-8028c89ff4c7", "historyId": "e74b47a6b541325cfd39bfc65f3a2847", "testCaseId": "e74b47a6b541325cfd39bfc65f3a2847", "fullName": "suits.test_orderflows.test_cash.test_phoneorder_cash.TestPhoneOrderCash#test_phoneorder_update_pay", "labels": [{"name": "epic", "value": "Orderflow"}, {"name": "feature", "value": "Phone order in Cash"}, {"name": "story", "value": "Phone Order Save and Update and Pay"}, {"name": "parentSuite", "value": "suits.test_orderflows.test_cash"}, {"name": "suite", "value": "test_phoneorder_cash"}, {"name": "subSuite", "value": "TestPhoneOrderCash"}, {"name": "host", "value": "LAPTOP-KKMKONCC"}, {"name": "thread", "value": "9204-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "suits.test_orderflows.test_cash.test_phoneorder_cash"}]}