{"name": "Add a Note to the Order", "status": "failed", "statusDetails": {"message": "AssertionError: Failed to add note\nassert None\n +  where None = add_note()\n +    where add_note = <logic.takeout_logic.Calculations object at 0x000001BB8B10CA60>.add_note\n +      where <logic.takeout_logic.Calculations object at 0x000001BB8B10CA60> = <test_cash.test_openorder_cash.TestOpenOrderCash object at 0x000001BB8B10F190>.calc", "trace": "self = <test_cash.test_openorder_cash.TestOpenOrderCash object at 0x000001BB8B10F190>\n\n    @allure.story(\"Order Modifications\")\n    @allure.title(\"Add a Note to the Order\")\n    @allure.description(\"Verifies that a note can be added to an order successfully.\")\n    def test_add_note(self):\n        with allure.step(\"Adding a note to the order\"):\n>           assert self.calc.add_note(), \"Failed to add note\"\nE           AssertionError: Failed to add note\nE           assert None\nE            +  where None = add_note()\nE            +    where add_note = <logic.takeout_logic.Calculations object at 0x000001BB8B10CA60>.add_note\nE            +      where <logic.takeout_logic.Calculations object at 0x000001BB8B10CA60> = <test_cash.test_openorder_cash.TestOpenOrderCash object at 0x000001BB8B10F190>.calc\n\nAutomation-logic\\suits\\test_orderflows\\test_cash\\test_openorder_cash.py:47: AssertionError"}, "description": "Verifies that a note can be added to an order successfully.", "steps": [{"name": "Adding a note to the order", "status": "failed", "statusDetails": {"message": "AssertionError: Failed to add note\nassert None\n +  where None = add_note()\n +    where add_note = <logic.takeout_logic.Calculations object at 0x000001BB8B10CA60>.add_note\n +      where <logic.takeout_logic.Calculations object at 0x000001BB8B10CA60> = <test_cash.test_openorder_cash.TestOpenOrderCash object at 0x000001BB8B10F190>.calc\n", "trace": "  File \"C:\\Users\\rutwik\\Automation\\Automation-logic\\suits\\test_orderflows\\test_cash\\test_openorder_cash.py\", line 47, in test_add_note\n    assert self.calc.add_note(), \"Failed to add note\"\n"}, "start": 1742914799101, "stop": 1742914814575}], "start": 1742914799101, "stop": 1742914814578, "uuid": "e388e9cb-e22d-47a5-adff-3e54e73387d9", "historyId": "99bda4d52fa825b8711463a080e99fc2", "testCaseId": "99bda4d52fa825b8711463a080e99fc2", "fullName": "suits.test_orderflows.test_cash.test_openorder_cash.TestOpenOrderCash#test_add_note", "labels": [{"name": "feature", "value": "Open order in Cash"}, {"name": "epic", "value": "Orderflow"}, {"name": "story", "value": "Order Modifications"}, {"name": "parentSuite", "value": "suits.test_orderflows.test_cash"}, {"name": "suite", "value": "test_openorder_cash"}, {"name": "subSuite", "value": "TestOpenOrderCash"}, {"name": "host", "value": "LAPTOP-KKMKONCC"}, {"name": "thread", "value": "13792-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "suits.test_orderflows.test_cash.test_openorder_cash"}]}