{"name": "test_individual_payments", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'Error Message: An element could not be located on the page using the given search parameters.; For documentation on t...ata\\\\Roaming\\\\npm\\\\node_modules\\\\appium\\\\node_modules\\\\@appium\\\\base-driver\\\\lib\\\\basedriver\\\\commands\\\\find.ts:75:12)' == True\n +  where 'Error Message: An element could not be located on the page using the given search parameters.; For documentation on t...ata\\\\Roaming\\\\npm\\\\node_modules\\\\appium\\\\node_modules\\\\@appium\\\\base-driver\\\\lib\\\\basedriver\\\\commands\\\\find.ts:75:12)' = paying_individually('card')\n +    where paying_individually = <logic.dining_logic.Dining object at 0x000001A3FC86A590>.paying_individually\n +      where <logic.dining_logic.Dining object at 0x000001A3FC86A590> = <test_dining_card.TestCashLog object at 0x000001A3FC8136A0>.dining", "trace": "self = <test_dining_card.TestCashLog object at 0x000001A3FC8136A0>\n\n    def test_individual_payments(self):\n>       assert self.dining.paying_individually(\"card\") == True\nE       AssertionError: assert 'Error Message: An element could not be located on the page using the given search parameters.; For documentation on t...ata\\\\Roaming\\\\npm\\\\node_modules\\\\appium\\\\node_modules\\\\@appium\\\\base-driver\\\\lib\\\\basedriver\\\\commands\\\\find.ts:75:12)' == True\nE        +  where 'Error Message: An element could not be located on the page using the given search parameters.; For documentation on t...ata\\\\Roaming\\\\npm\\\\node_modules\\\\appium\\\\node_modules\\\\@appium\\\\base-driver\\\\lib\\\\basedriver\\\\commands\\\\find.ts:75:12)' = paying_individually('card')\nE        +    where paying_individually = <logic.dining_logic.Dining object at 0x000001A3FC86A590>.paying_individually\nE        +      where <logic.dining_logic.Dining object at 0x000001A3FC86A590> = <test_dining_card.TestCashLog object at 0x000001A3FC8136A0>.dining\n\nAutomation-logic\\suits\\test_dining\\test_dining_card.py:87: AssertionError"}, "start": 1743688006387, "stop": 1743688093156, "uuid": "287a228c-1c0e-4775-860c-030cc152c3fa", "historyId": "36ef8b975e6f30dff9a1852a3c688616", "testCaseId": "36ef8b975e6f30dff9a1852a3c688616", "fullName": "suits.test_dining.test_dining_card.TestCashLog#test_individual_payments", "labels": [{"name": "parentSuite", "value": "suits.test_dining"}, {"name": "suite", "value": "test_dining_card"}, {"name": "subSuite", "value": "TestCashLog"}, {"name": "host", "value": "LAPTOP-KKMKONCC"}, {"name": "thread", "value": "19540-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "suits.test_dining.test_dining_card"}]}