{"name": "Process a phone order with Save and then Pay", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'ERROR IS Message: \\nStacktrace:\\nNoSuchElementError: An element could not be located on the page using the given sear...ata\\\\Roaming\\\\npm\\\\node_modules\\\\appium\\\\node_modules\\\\@appium\\\\base-driver\\\\lib\\\\basedriver\\\\commands\\\\find.ts:75:12)' == True\n +  where 'ERROR IS Message: \\nStacktrace:\\nNoSuchElementError: An element could not be located on the page using the given sear...ata\\\\Roaming\\\\npm\\\\node_modules\\\\appium\\\\node_modules\\\\@appium\\\\base-driver\\\\lib\\\\basedriver\\\\commands\\\\find.ts:75:12)' = order('Phone Order')\n +    where order = <logic.takeout_logic.Calculations object at 0x0000021A47081370>.order\n +      where <logic.takeout_logic.Calculations object at 0x0000021A47081370> = <test_phoneorder_card.TestPhoneOrderCard object at 0x0000021A47394170>.phone", "trace": "self = <test_phoneorder_card.TestPhoneOrderCard object at 0x0000021A47394170>\n\n    @allure.story(\"Phone Order Save and Pay\")\n    @allure.title(\"Process a phone order with Save and then Pay\")\n    def test_phoneorder_save_pay(self):\n    \n>       assert self.phone.order(\"Phone Order\") == True\nE       AssertionError: assert 'ERROR IS Message: \\nStacktrace:\\nNoSuchElementError: An element could not be located on the page using the given sear...ata\\\\Roaming\\\\npm\\\\node_modules\\\\appium\\\\node_modules\\\\@appium\\\\base-driver\\\\lib\\\\basedriver\\\\commands\\\\find.ts:75:12)' == True\nE        +  where 'ERROR IS Message: \\nStacktrace:\\nNoSuchElementError: An element could not be located on the page using the given sear...ata\\\\Roaming\\\\npm\\\\node_modules\\\\appium\\\\node_modules\\\\@appium\\\\base-driver\\\\lib\\\\basedriver\\\\commands\\\\find.ts:75:12)' = order('Phone Order')\nE        +    where order = <logic.takeout_logic.Calculations object at 0x0000021A47081370>.order\nE        +      where <logic.takeout_logic.Calculations object at 0x0000021A47081370> = <test_phoneorder_card.TestPhoneOrderCard object at 0x0000021A47394170>.phone\n\nsuits\\test_orderflows\\test_card\\test_phoneorder_card.py:29: AssertionError"}, "start": 1741780403398, "stop": 1741780413732, "uuid": "0706e6fb-0c75-43ab-9735-fb0689def6ad", "historyId": "9979c322a3eae085832f011ab6e7b51b", "testCaseId": "9979c322a3eae085832f011ab6e7b51b", "fullName": "suits.test_orderflows.test_card.test_phoneorder_card.TestPhoneOrderCard#test_phoneorder_save_pay", "labels": [{"name": "feature", "value": "Sanity Sheet"}, {"name": "story", "value": "Phone Order Save and Pay"}, {"name": "parentSuite", "value": "suits.test_orderflows.test_card"}, {"name": "suite", "value": "test_phoneorder_card"}, {"name": "subSuite", "value": "TestPhoneOrderCard"}, {"name": "host", "value": "LAPTOP-KKMKONCC"}, {"name": "thread", "value": "8692-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "suits.test_orderflows.test_card.test_phoneorder_card"}]}