{"name": "Select 'Open Order' for Cash Payment", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'ERROR IS Message: \\nStacktrace:\\nNoSuchElementError: An element could not be located on the page using the given sear...ata\\\\Roaming\\\\npm\\\\node_modules\\\\appium\\\\node_modules\\\\@appium\\\\base-driver\\\\lib\\\\basedriver\\\\commands\\\\find.ts:75:12)' == True\n +  where 'ERROR IS Message: \\nStacktrace:\\nNoSuchElementError: An element could not be located on the page using the given sear...ata\\\\Roaming\\\\npm\\\\node_modules\\\\appium\\\\node_modules\\\\@appium\\\\base-driver\\\\lib\\\\basedriver\\\\commands\\\\find.ts:75:12)' = order('Open Order')\n +    where order = <logic.takeout_logic.Calculations object at 0x0000022338E75D50>.order\n +      where <logic.takeout_logic.Calculations object at 0x0000022338E75D50> = <test_cash.test_openorder_cash.TestOpenOrderCash object at 0x000002233AF22D70>.calc", "trace": "self = <test_cash.test_openorder_cash.TestOpenOrderCash object at 0x000002233AF22D70>\n\n    @allure.story(\"Order Creation\")\n    @allure.title(\"Select 'Open Order' for Cash Payment\")\n    @allure.description(\"Verifies that the user can successfully select the 'Open Order' option in POS.\")\n    def test_openorder_btn(self):\n>       assert self.calc.order(\"Open Order\") == True\nE       AssertionError: assert 'ERROR IS Message: \\nStacktrace:\\nNoSuchElementError: An element could not be located on the page using the given sear...ata\\\\Roaming\\\\npm\\\\node_modules\\\\appium\\\\node_modules\\\\@appium\\\\base-driver\\\\lib\\\\basedriver\\\\commands\\\\find.ts:75:12)' == True\nE        +  where 'ERROR IS Message: \\nStacktrace:\\nNoSuchElementError: An element could not be located on the page using the given sear...ata\\\\Roaming\\\\npm\\\\node_modules\\\\appium\\\\node_modules\\\\@appium\\\\base-driver\\\\lib\\\\basedriver\\\\commands\\\\find.ts:75:12)' = order('Open Order')\nE        +    where order = <logic.takeout_logic.Calculations object at 0x0000022338E75D50>.order\nE        +      where <logic.takeout_logic.Calculations object at 0x0000022338E75D50> = <test_cash.test_openorder_cash.TestOpenOrderCash object at 0x000002233AF22D70>.calc\n\nsuits\\test_orderflows\\test_cash\\test_openorder_cash.py:23: AssertionError"}, "description": "Verifies that the user can successfully select the 'Open Order' option in POS.", "start": 1741860648930, "stop": 1741860659429, "uuid": "1bae3cb5-a3ea-49d7-a04c-cab0973ad1cf", "testCaseId": "1d7d7ec0945bf403cfe2546fa05ec601", "fullName": "suits.test_orderflows.test_cash.test_openorder_cash.TestOpenOrderCash#test_openorder_btn"}