{"uuid": "28cf58e9-0e2c-4a5a-9fea-2974edf47eb5", "children": ["760b605f-f849-4863-b2d3-3b5894bc053a"], "befores": [{"name": "capture_screenshot_on_failure", "status": "passed", "start": 1742918238539, "stop": 1742918238539}], "afters": [{"name": "capture_screenshot_on_failure::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'\n", "trace": "  File \"C:\\Users\\rutwik\\miniconda3\\envs\\automation\\lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\rutwik\\miniconda3\\envs\\automation\\lib\\site-packages\\_pytest\\fixtures.py\", line 907, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\rutwik\\Automation\\Automation-logic\\conftest.py\", line 102, in capture_screenshot_on_failure\n    if request.node.rep_call.failed:\n"}, "start": 1742918246957, "stop": 1742918246987}], "start": 1742918238539, "stop": 1742918246987}