{"name": "Process a phone order with Save and then Pay", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'ERROR IS Message: \\nStacktrace:\\nNoSuchElementError: An element could not be located on the page using the given sear...ata\\\\Roaming\\\\npm\\\\node_modules\\\\appium\\\\node_modules\\\\@appium\\\\base-driver\\\\lib\\\\basedriver\\\\commands\\\\find.ts:75:12)' == True\n +  where 'ERROR IS Message: \\nStacktrace:\\nNoSuchElementError: An element could not be located on the page using the given sear...ata\\\\Roaming\\\\npm\\\\node_modules\\\\appium\\\\node_modules\\\\@appium\\\\base-driver\\\\lib\\\\basedriver\\\\commands\\\\find.ts:75:12)' = order('Phone Order')\n +    where order = <logic.takeout_logic.Calculations object at 0x000001CFB57F8B50>.order\n +      where <logic.takeout_logic.Calculations object at 0x000001CFB57F8B50> = <test_phoneorder_card.TestPhoneOrderCard object at 0x000001CFB57DE890>.phone", "trace": "self = <test_phoneorder_card.TestPhoneOrderCard object at 0x000001CFB57DE890>\n\n    @allure.story(\"Phone Order Save and Pay\")\n    @allure.title(\"Process a phone order with Save and then Pay\")\n    def test_phoneorder_save_pay(self):\n    \n>       assert self.phone.order(\"Phone Order\") == True\nE       AssertionError: assert 'ERROR IS Message: \\nStacktrace:\\nNoSuchElementError: An element could not be located on the page using the given sear...ata\\\\Roaming\\\\npm\\\\node_modules\\\\appium\\\\node_modules\\\\@appium\\\\base-driver\\\\lib\\\\basedriver\\\\commands\\\\find.ts:75:12)' == True\nE        +  where 'ERROR IS Message: \\nStacktrace:\\nNoSuchElementError: An element could not be located on the page using the given sear...ata\\\\Roaming\\\\npm\\\\node_modules\\\\appium\\\\node_modules\\\\@appium\\\\base-driver\\\\lib\\\\basedriver\\\\commands\\\\find.ts:75:12)' = order('Phone Order')\nE        +    where order = <logic.takeout_logic.Calculations object at 0x000001CFB57F8B50>.order\nE        +      where <logic.takeout_logic.Calculations object at 0x000001CFB57F8B50> = <test_phoneorder_card.TestPhoneOrderCard object at 0x000001CFB57DE890>.phone\n\nAutomation-logic\\suits\\test_orderflows\\test_card\\test_phoneorder_card.py:40: AssertionError"}, "start": 1742916821374, "stop": 1742916831908, "uuid": "4b9c3b15-f6f8-4a0d-b6d8-04c6929e10b6", "historyId": "9979c322a3eae085832f011ab6e7b51b", "testCaseId": "9979c322a3eae085832f011ab6e7b51b", "fullName": "suits.test_orderflows.test_card.test_phoneorder_card.TestPhoneOrderCard#test_phoneorder_save_pay", "labels": [{"name": "feature", "value": "Phone order in Card"}, {"name": "epic", "value": "Orderflow"}, {"name": "story", "value": "Phone Order Save and Pay"}, {"name": "parentSuite", "value": "suits.test_orderflows.test_card"}, {"name": "suite", "value": "test_phoneorder_card"}, {"name": "subSuite", "value": "TestPhoneOrderCard"}, {"name": "host", "value": "LAPTOP-KKMKONCC"}, {"name": "thread", "value": "15160-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "suits.test_orderflows.test_card.test_phoneorder_card"}]}