{"uuid": "6836b3bb-f767-4429-bdac-0003b1c56ffa", "children": ["8b49855e-3da6-429d-9752-426c561781dd"], "befores": [{"name": "capture_screenshot_on_failure", "status": "passed", "start": 1742916375940, "stop": 1742916375940}], "afters": [{"name": "capture_screenshot_on_failure::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'\n", "trace": "  File \"C:\\Users\\rutwik\\miniconda3\\envs\\automation\\lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\rutwik\\miniconda3\\envs\\automation\\lib\\site-packages\\_pytest\\fixtures.py\", line 907, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\rutwik\\Automation\\Automation-logic\\conftest.py\", line 102, in capture_screenshot_on_failure\n    if request.node.rep_call.failed:\n"}, "start": 1742916384828, "stop": 1742916384854}], "start": 1742916375940, "stop": 1742916384854}