{"uuid": "9aea440f-4ecb-486b-bcc4-892129ab0403", "children": ["1090c4cd-ca0a-4da6-b78c-9505fa22f61b"], "befores": [{"name": "capture_screenshot_on_failure", "status": "passed", "start": 1743600782119, "stop": 1743600782119}], "afters": [{"name": "capture_screenshot_on_failure::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'\n", "trace": "  File \"C:\\Users\\rutwik\\miniconda3\\envs\\automation\\lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\rutwik\\miniconda3\\envs\\automation\\lib\\site-packages\\_pytest\\fixtures.py\", line 907, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\rutwik\\Automation\\Automation-logic\\conftest.py\", line 102, in capture_screenshot_on_failure\n    if request.node.rep_call.failed:\n"}, "start": 1743600803958, "stop": 1743600804027}], "start": 1743600782119, "stop": 1743600804027}