{"uuid": "9d180962-dc9b-4682-afeb-ec8dbf593129", "children": ["754f62cc-cfd9-459a-9765-10bb3b09261f"], "befores": [{"name": "capture_screenshot_on_failure", "status": "passed", "start": 1743686097284, "stop": 1743686097284}], "afters": [{"name": "capture_screenshot_on_failure::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'\n", "trace": "  File \"C:\\Users\\rutwik\\miniconda3\\envs\\automation\\lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\rutwik\\miniconda3\\envs\\automation\\lib\\site-packages\\_pytest\\fixtures.py\", line 907, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\rutwik\\Automation\\Automation-logic\\conftest.py\", line 107, in capture_screenshot_on_failure\n    if request.node.rep_call.failed:\n"}, "start": 1743686101632, "stop": 1743686101703}], "start": 1743686097284, "stop": 1743686101703}